# Generated by Django 4.2.3 on 2023-08-04 11:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('food', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TestTable1',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uname', models.CharField(max_length=122)),
                ('date', models.CharField(max_length=122)),
                ('email', models.CharField(max_length=122)),
                ('number', models.CharField(max_length=122)),
                ('food1', models.CharField(max_length=122)),
                ('restaurant', models.CharField(max_length=122)),
                ('drinks', models.CharField(max_length=122)),
                ('soups', models.CharField(max_length=122)),
                ('dishes', models.CharField(max_length=122)),
                ('order', models.CharField(max_length=122)),
            ],
        ),
    ]
